terms:
  - id: "http://www.jbe-platform.com/content/journals/15720276"
    term: "Annual Review of Cognitive Linguistics"
  - id: "https://academic.oup.com/applij/"
    term: "Applied Linguistics"
  - id: "https://www.degruyter.com/view/j/alr"
    term: "Applied Linguistics Review"
  - id: "https://www.cambridge.org/core/journals/applied-psycholinguistics"
    term: "Applied Psycholinguistics"
  - id: "https://www.springer.com/psychology/cognitive+psychology/journal/13428"
    term: "Behavior Research Methods"
  - id: "https://www.cambridge.org/core/journals/bilingualism-language-and-cognition"
    term: "Bilingualism: Language and Cognition"
  - id: "https://www.tandfonline.com/loi/rbje20"
    term: "British Journal of Educational Studies"
  - id: "https://www.utpjournals.press/loi/cmlr"
    term: "Canadian Modern Language Review"
  - id: "journals.elsevier.com/cognition"
    term: "Cognition"
  - id: "https://www.journals.elsevier.com/cognitive-psychology/"
    term: "Cognitive Psychology"
  - id: "https://www.tandfonline.com/loi/ncal20"
    term: "Computer Assisted Language Learning"
  - id: "https://academic.oup.com/eltj"
    term: "ELT Journal"
  - id: "https://www.tandfonline.com/loi/ceds20"
    term: "Educational Studies"
  - id: "https://www.journals.elsevier.com/english-for-specific-purposes/"
    term: "English for Specific Purposes"
  - id: "https://www.tandfonline.com/loi/cete20"
    term: "European Journal of Teacher Education"
  - id: "https://onlinelibrary.wiley.com/journal/19449720"
    term: "Foreign Language Annals"
  - id: "https://www.tandfonline.com/journals/rill20"
    term: "Innovation in Language Learning and Teaching"    
  - id: "https://www.degruyter.com/view/j/iprg"
    term: "Intercultural Pragmatics"
  - id: "https://www.tandfonline.com/toc/rbeb20/current"
    term: "International Journal of Bilingual Education and Bilingualism"
  - id: "http://journals.sagepub.com/home/ijb/"
    term: "International Journal of Bilingualism"
  - id: "https://www.journals.elsevier.com/international-journal-of-educational-research"
    term: "International Journal of Educational Research"
  - id: "https://www.degruyter.com/view/j/iral"
    term: "International Review of Applied Linguistics"
  - id: "https://www.cambridge.org/core/journals/journal-of-child-language"
    term: "Journal of Child Language"
  - id: "https://www.journals.elsevier.com/journal-of-communication-disorders/"
    term: "Journal of Communication Disorders"
  - id: "https://www.cambridge.org/core/journals/journal-of-french-language-studies"
    term: "Journal of French Language Studies"
  - id: "http://journals.sagepub.com/home/jls"
    term: "Journal of Language and Social Psychology"
  - id: "https://www.tandfonline.com/loi/hlie20"
    term: "Journal of Language, Identity & Education"
  - id: "https://www.journals.elsevier.com/journal-of-memory-and-language/"
    term: "Journal of Memory and Language"
  - id: "https://www.tandfonline.com/loi/rmmm20"
    term: "Journal of Multilingual and Multicultural Development"
  - id: "https://link.springer.com/journal/10936"
    term: "Journal of Psycholinguistic Research"
  - id: "https://benjamins.com/catalog/jslp"
    term: "Journal of Second Language Pronunciation"
  - id: "https://jslhr.pubs.asha.org"
    term: "Journal of Speech, Language, and Hearing Research"
  - id: "https://www.tandfonline.com/loi/HLAC20"
    term: "Language Acquisition"
  - id: "https://www.tandfonline.com/loi/rmla20"
    term: "Language Awareness"
  - id: "https://www.tandfonline.com/loi/rlcc20"
    term: "Language Culture and Curriculum"
  - id: "https://onlinelibrary.wiley.com/journal/14679922"
    term: "Language Learning"
  - id: "http://www.lltjournal.org"
    term: "Language Learning and Technology"
  - id: "https://www.journals.elsevier.com/language-sciences/"
    term: "Language Sciences"
  - id: "https://www.cambridge.org/core/journals/language-teaching"
    term: "Language Teaching"
  - id: "http://journals.sagepub.com/home/ltr"
    term: "Language Teaching Research"
  - id: "http://journals.sagepub.com/home/ltj"
    term: "Language Testing"
  - id: "https://www.tandfonline.com/toc/plcp20/current"
    term: "Language and Cognitive Processes"
  - id: "https://www.tandfonline.com/loi/rlae20"
    term: "Language and Education"
  - id: "https://www.tandfonline.com/loi/rmli20"
    term: "Language and Intercultural Communication"
  - id: "https://www.journals.elsevier.com/lingua/"
    term: "Lingua"
  - id: "https://benjamins.com/catalog/lab"
    term: "Linguistic Approaches to Bilingualism"
  - id: "https://www.journals.elsevier.com/linguistics-and-education"
    term: "Linguistics and Education"
  - id: "https://onlinelibrary.wiley.com/journal/17414369"
    term: "Literacy"
  - id: "https://www.springer.com/psychology/cognitive+psychology/journal/13421"
    term: "Memory and Cognition"
  - id: "https://www.tandfonline.com/loi/hmet20"
    term: "Metaphor and Symbol"
  - id: "https://www.degruyter.com/view/j/mult"
    term: "Multilingua - Journal of Cross-Cultural and Interlanguage Communication"
  - id: "http://www.ugr.es/~portalin/"
    term: "Porta Linguarum"
  - id: "https://benjamins.com/catalog/ps"
    term: "Pragmatics and Society"
  - id: "https://www.cambridge.org/core/journals/recall"
    term: "ReCALL"
  - id: "https://benjamins.com/catalog/resla"
    term: "Revista Española de Lingüística Aplicada /Spanish Journal of Applied Linguistics"
  - id: "http://journals.sagepub.com/loi/slr"
    term: "Second Language Research"
  - id: "https://www.cambridge.org/core/journals/studies-in-second-language-acquisition"
    term: "Studies in Second Language Acquisition"
  - id: "https://www.journals.elsevier.com/system"
    term: "System"
  - id: "https://onlinelibrary.wiley.com/journal/15457249"
    term: "TESOL Quarterly"
  - id: "https://onlinelibrary.wiley.com/journal/15404781"
    term: "The Modern Language Journal"
  - id: "http://vialjournal.webs.uvigo.es"
    term: "Vial-Vigo International Journal of Applied Linguistics"
  - id: "https://onlinelibrary.wiley.com/journal/1467971x"
    term: "World Englishes"
  - id: "other_journal"
    term: "Other"
