terms:
  - id: 1
    term: "Annual Review of Cognitive Linguistics"
  - id: 2
    term: "Applied Linguistics"
  - id: 3
    term: "Applied Psycholinguistics"
  - id: 4
    term: "Behavior Research Methods"
  - id: 5
    term: "Bilingualism: Language and Cognition"
  - id: 6
    term: "British Journal of Educational Studies"
  - id: 7
    term: "Canadian Modern Language Review"
  - id: 8
    term: "Cognition"
  - id: 9
    term: "Cognitive Psychology"
  - id: 10
    term: "Dutch Journal of Applied Linguistics"
  - id: 11
    term: "ELT Journal"
  - id: 12
    term: "Educational Studies"
  - id: 13
    term: "European Journal of Teacher Education"
  - id: 14
    term: "Foreign Language Annals"
  - id: 15
    term: "Frontiers: The Interdisciplinary Journal of Study Abroad"
  - id: 16
    term: "Innovation in Language Learning and Teaching"
  - id: 17
    term: "International Journal of Applied Linguistics"
  - id: 18
    term: "International Journal of Bilingual Education and Bilingualism"
  - id: 19
    term: "International Journal of Educational Research"
  - id: 20
    term: "International Journal of Speech Technology"
  - id: 21
    term: "International Review of Applied Linguistics"
  - id: 22
    term: "Journal of Child Language"
  - id: 23
    term: "Journal of Educational and Social Research"
  - id: 24
    term: "Journal of Immersion and Content-Based Language Education"
  - id: 25
    term: "Journal of Language and Social Psychology"
  - id: 26
    term: "Journal of Memory and Language"
  - id: 27
    term: "Journal of Multilingual and Multicultural Development"
  - id: 28
    term: "Journal of Psycholinguistic Research"
  - id: 29
    term: "Journal of Speech, Language, and Hearing Research"
  - id: 30
    term: "Language Acquisition"
  - id: 31
    term: "Language Awareness"
  - id: 32
    term: "Language Learning"
  - id: 33
    term: "Language Learning and Technology"
  - id: 34
    term: "Language Sciences"
  - id: 35
    term: "Language Teaching Research"
  - id: 36
    term: "Language Testing"
  - id: 37
    term: "Language and Cognitive Processes"
  - id: 38
    term: "Language and Education"
  - id: 39
    term: "Lingua"
  - id: 40
    term: "Linguistic Approaches to Bilingualism"
  - id: 41
    term: "Linguistics and Education"
  - id: 42
    term: "Memory and Cognition"
  - id: 43
    term: "Reading in a Foreign Language"
  - id: 44
    term: "Second Language Research"
  - id: 45
    term: "Studies in Second Language Acquisition"
  - id: 46
    term: "Studies in Second Language Learning and Teaching"
  - id: 47
    term: "System"
  - id: 48
    term: "TESL-EJ"
  - id: 49
    term: "TESOL Canada Journal"
  - id: 50
    term: "TESOL Quarterly"
  - id: 51
    term: "TESOL in Context"
  - id: 52
    term: "The Language Learning Journal"
  - id: 53
    term: "The Modern Language Journal"
  - id: 54
    term: "The Quarterly Journal of Experimental Psychology"
  - id: 55
    term: "Other"
