terms:
  - id: 1
    term: "Annual Review of Cognitive Linguistics"
  - id: 2
    term: "Applied Linguistics"
  - id: 56
    term: "Applied Linguistics Review"
  - id: 3
    term: "Applied Psycholinguistics"
  - id: 4
    term: "Behavior Research Methods"
  - id: 5
    term: "Bilingualism: Language and Cognition"
  - id: 6
    term: "British Journal of Educational Studies"
  - id: 7
    term: "Canadian Modern Language Review"
  - id: 8
    term: "Cognition"
  - id: 9
    term: "Cognitive Psychology"
  - id: 57
    term: "Computer Assisted Language Learning"
  - id: 11
    term: "ELT Journal"
  - id: 12
    term: "Educational Studies"
  - id: 58
    term: "English for Specific Purposes"
  - id: 13
    term: "European Journal of Teacher Education"
  - id: 14
    term: "Foreign Language Annals"
  - id: 59
    term: "Intercultural Pragmatics"
  - id: 18
    term: "International Journal of Bilingual Education and Bilingualism"
  - id: 60
    term: "International Journal of Bilingualism"
  - id: 19
    term: "International Journal of Educational Research"
  - id: 21
    term: "International Review of Applied Linguistics"
  - id: 22
    term: "Journal of Child Language"
  - id: 61
    term: "Journal of Communication Disorders"
  - id: 62
    term: "Journal of French Language Studies"
  - id: 25
    term: "Journal of Language and Social Psychology"
  - id: 26
    term: "Journal of Memory and Language"
  - id: 27
    term: "Journal of Multilingual and Multicultural Development"
  - id: 28
    term: "Journal of Psycholinguistic Research"
  - id: 29
    term: "Journal of Speech, Language, and Hearing Research"
  - id: 30
    term: "Language Acquisition"
  - id: 31
    term: "Language Awareness"
  - id: 63
    term: "Language Culture and Curriculum"
  - id: 32
    term: "Language Learning"
  - id: 33
    term: "Language Learning and Technology"
  - id: 34
    term: "Language Sciences"
  - id: 64
    term: "Language Teaching"
  - id: 35
    term: "Language Teaching Research"
  - id: 36
    term: "Language Testing"
  - id: 37
    term: "Language and Cognitive Processes"
  - id: 38
    term: "Language and Education"
  - id: 65
    term: "Language and Intercultural Communication"
  - id: 39
    term: "Lingua"
  - id: 40
    term: "Linguistic Approaches to Bilingualism"
  - id: 41
    term: "Linguistics and Education"
  - id: 66
    term: "Literacy"
  - id: 42
    term: "Memory and Cognition"
  - id: 67
    term: "Metaphor and Symbol"
  - id: 68
    term: "Multilingua - Journal of Cross-Cultural and Interlanguage Communication"
  - id: 69
    term: "Porta Linguarum"
  - id: 70
    term: "Pragmatics and Society"
  - id: 71
    term: "ReCALL"
  - id: 72
    term: "Revista Española de Lingüística Aplicada /Spanish Journal of Applied Linguistics"
  - id: 44
    term: "Second Language Research"
  - id: 45
    term: "Studies in Second Language Acquisition"
  - id: 47
    term: "System"
  - id: 50
    term: "TESOL Quarterly"
  - id: 53
    term: "The Modern Language Journal"
  - id: 73
    term: "Vial-Vigo International Journal of Applied Linguistics"
  - id: 74
    term: "World Englishes"
  - id: 55
    term: "Other"
