terms:
  - id: 1
    term: "Adolescent learners"
  - id: 2
    term: "Adults learners"
  - id: 3
    term: "Artificial language learners"
  - id: 4
    term: "Bilinguals"
  - id: 5
    term: "First language attriters"
  - id: 6
    term: "First language learners"
  - id: 7
    term: "Foreign language learners"
  - id: 8
    term: "Heritage speakers"
  - id: 9
    term: "Language users"
  - id: 10
    term: "Monolinguals"
  - id: 11
    term: "Native speakers"
  - id: 12
    term: "Parent"
  - id: 13
    term: "Policy-makers"
  - id: 14
    term: "Primary school"
  - id: 15
    term: "Secondary school"
  - id: 16
    term: "Second language learners"
  - id: 17
    term: "Teacher trainees"
  - id: 18
    term: "Teachers"
  - id: 19
    term: "Young learners"
  - id: 20
    term: "Other"